// packages/home/src/routes/protocol.love/index.svelte
<script>
import Head from '@cogov/home-ui/Head.svelte'
import Nav from '@cogov/home-ui/Nav.svelte'
import Footer from '@cogov/home-ui/Footer.svelte'
import Header from './_header.svelte'
import Content from './_content.svelte'
</script>

<svelte:head>
	<Head
		title="Protocol.Love: Fostering the emergence of a socioeconomic system infused with Loving Kindness"
	></Head>
</svelte:head>

<div class="protocol-page">
	<Nav></Nav>
	<Header></Header>
	<Content></Content>

	<Footer></Footer>
</div>

<style type="text/scss">
.protocol-page {
	margin-top: 7rem;
	height: 100%;
	width: 100%;
	position: relative;
}
</style>

// apps/www/src/routes/protocol.love/index.tsx
import { Head, Title } from 'solid-start'
import { Page_protocollove } from '@cogov/ui'
export default function C_protocollove() {
	return [
		<Head>
			<Title>Protocol.Love: Fostering the emergence of a socioeconomic system infused with Loving Kindness</Title>
		</Head>,
		<Page_protocollove/>,
	]
}
